CREATE TABLE IF NOT EXISTS HikingTrail (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    code CHAR(36) NOT NULL DEFAULT UUID(),
    difficulty_level_id INT UNSIGNED,
    terrain_type_id INT UNSIGNED NOT NULL,
    trail_type_id INT UNSIGNED NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    pet_friendly BOOLEAN DEFAULT FALSE,
    start_time DATETIME NOT NULL,
    end_time DATETIME NOT NULL,
    ubication_latitude DECIMAL(9, 6) NOT NULL,
    ubication_longitude DECIMAL(9, 6) NOT NULL,
    deleted BOOLEAN DEFAULT FALSE,
    generated_by_fit_file BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (difficulty_level_id) REFERENCES DifficultyLevel(id),
    FOREIGN KEY (terrain_type_id) REFERENCES TerrainType(id),
    FOREIGN KEY (trail_type_id) REFERENCES TrailType(id)
);