CREATE TABLE IF NOT EXISTS Metrics (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    code CHAR(36) NOT NULL DEFAULT UUID(),
    hiking_trail_id INT UNSIGNED,
    distance INT NOT NULL COMMENT 'Distancia total del recorrido en metros. TotalDistance del archivo .fit.',
    duration DECIMAL(13, 3) UNSIGNED COMMENT 'Duración total del recorrido en segundos. TotalElapsedTime del archivo .fit.',
    steps INT COMMENT 'Calculado como TotalCycles * 2 del archivo .fit.',
    calories INT COMMENT 'TotalCalories del archivo .fit.',
    average_pace DECIMAL(13, 6) COMMENT 'Expresada en minutos por kilómetro. Calculado como 60 (s) / (averageSpeed (m/s) * 3.6)',
    max_pace DECIMAL(13, 6) COMMENT 'Expresada en minutos por kilómetro. Calculado como 60 (s) / (maxSpeed (m/s) * 3.6)',
    elevation_gain DECIMAL(10, 2) COMMENT 'TotalAscent del archivo .fit.',
    elevation_loss DECIMAL(10, 2) COMMENT 'TotalDescent del archivo .fit.',
    average_speed DECIMAL(13, 6) COMMENT 'Expresada en m/s. Multiplicar por 3.6 para obtener km/h. AverageSpeed del archivo .fit.',
    max_speed DECIMAL(13, 6) COMMENT 'Expresada en m/s. Multiplicar por 3.6 para obtener km/h. MaxSpeed del archivo .fit.',
    average_heart_rate INT COMMENT 'Frecuencia cardíaca promedio en pulsaciones por minuto. AverageHeartRate del archivo .fit.',
    max_heart_rate INT COMMENT 'Frecuencia cardíaca máxima en pulsaciones por minuto. MaxHeartRate del archivo .fit.',
    min_heart_rate INT COMMENT 'Frecuencia cardíaca mínima en pulsaciones por minuto. MinHeartRate del archivo .fit.',
    average_cadence DECIMAL(5, 2) COMMENT 'Cadencia promedio en pasos por minuto. AverageCadence del archivo .fit.',
    max_cadence DECIMAL(5, 2) COMMENT 'Cadencia máxima en pasos por minuto. MaxCadence del archivo .fit.',
    max_altitude DECIMAL(10, 2) COMMENT 'Altitud máxima alcanzada en metros. MaxAltitude del archivo .fit.',
    min_altitude DECIMAL(10, 2) COMMENT 'Altitud mínima alcanzada en metros. MinAltitude del archivo .fit.',
    total_training_effect DECIMAL(5, 2) COMMENT 'Efecto total del entrenamiento. TotalTrainingEffect del archivo .fit.',
    training_stress_score DECIMAL(5, 2) COMMENT 'Puntuación de estrés del entrenamiento. TrainingStressScore del archivo .fit.',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (hiking_trail_id) REFERENCES HikingTrail(id)
);