CREATE TABLE IF NOT EXISTS Images (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    code CHAR(36) NOT NULL DEFAULT (UUID()),
    hiking_trail_id INT UNSIGNED,
    image_url VARCHAR(255) NOT NULL,
    order_index INT UNSIGNED NOT NULL DEFAULT 0,
    deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (hiking_trail_id) REFERENCES HikingTrail(id)
);