CREATE TABLE IF NOT EXISTS Location (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    code CHAR(36) NOT NULL DEFAULT UUID(),
    hiking_trail_id INT UNSIGNED NOT NULL,
    country VARCHAR(100),
    country_code CHAR(2),
    state VARCHAR(100),
    state_code CHAR(10),
    county VARCHAR(100),
    county_code CHAR(10),
    city VARCHAR(100),
    post_code VARCHAR(20),
    district VARCHAR(100),
    suburb VARCHAR(100),
    street VARCHAR(100),
    house_number INT UNSIGNED,
    formatted_address VARCHAR(255),
    address_line1 VARCHAR(255),
    address_line2 VARCHAR(255),
    category VARCHAR(100),
    result_type VARCHAR(50),
    deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (hiking_trail_id) REFERENCES HikingTrail(id)
);